const empty = "";
export default [
  { type: "city", value: empty, text: "עיר" },
  { type: "street", value: empty, text: "רחוב" },
  { type: "streetNumber", value: empty, text: "מספר בית" },
  { type: "entrance", value: empty, text: "כניסה" },
  { type: "neighborhood", value: empty, text: "שכונה" },
  { type: "area", value: empty, text: "אזור" },
  { type: "assetType", value: empty, text: "סוג נכס" },
  { type: "assetState", value: empty, text: "מצב הנכס" },
  { type: "balconies", value: empty, text: "מרפסות" },
  { type: "floor", value: empty, text: "קומה" },
  { type: "parking", value: empty, text: "חניה" },
  { type: "totalFloors", value: empty, text: "קומות בבניין" },
  { type: "rooms", value: empty, text: "חדרים" },
  { type: "squareMetersBuilt", value: empty, text: 'מ"ר בנוי' },
  { type: "squareMetersGarden", value: empty, text: 'מ"ר גינה' },
  { type: "description", value: empty, text: "תיאור" },
  { type: "price", value: empty, text: "מחיר" },
  { type: "entranceDate", value: new Date(), text: "תאריך כניסה", name: 'date' },
  { type: "exclusivity", value: empty, text: "בלעדיות", name: "attributes" },
  { type: "airConditioned", value: empty, text: "מיזוג", name: "attributes" },
  { type: "kitchen", value: empty, text: "מטבח", name: "attributes" },
  { type: "kosherKithecn", value: empty, text: "מטבח כשר", name: "attributes" },
  { type: "lift", value: empty, text: "מעלית", name: "attributes" },
  { type: "bars", value: empty, text: "סורגים", name: "attributes" },
  { type: "renovated", value: empty, text: "משופץ", name: "attributes" },
  { type: "disabledAccess", value: empty, text: "גישה לנכים", name: "attributes" },
  { type: "safeSpace", value: empty, text: 'ממ"ד', name: "attributes" },
  { type: "pandorDoor", value: empty, text: "דלתות פנדור", name: "attributes" },
  { type: "warehouse", value: empty, text: "מחסן", name: "attributes" },
  { type: "furniture", value: empty, text: "ריהוט", name: "attributes" },
  { type: "livingUnit", value: empty, text: "יחדית דיור", name: "attributes" },
  { type: "tadiranAirConditioned", value: empty, text: "מזגן תדיראן", name: "attributes" },
  { type: "furnitureDescription", value: empty, text: "תיאור ריהוט" },
  { type: "imageBase64", value: empty, text: "תמונות" },
  { type: "videoBase64", value: empty, text: "סרטונים" }
];
