const empty = "";
export default [
  { type: "city", value: empty, text: "עיר" },
  { type: "street", value: empty, text: "רחוב" , notReuired: true},
  { type: "streetNumber", value: empty, text: "מספר בית" , notReuired: true},
  { type: "entrance", value: empty, text: "כניסה" , notReuired: true},
  { type: "neighborhood", value: empty, text: "שכונה" , notReuired: true},
  { type: "area", value: empty, text: "אזור" , notReuired: true},
  { type: "floor", value: 0, text: "קומה", notReuired: true },
  { type: "totalFloors", value: 0, text: "קומות בבניין", notReuired: true },
  { type: "rooms", value: 0, text: "חדרים", notReuired: true },
  { type: "squareMetersBuilt", value: 0, text: 'מ"ר בנוי', notReuired: true },
  { type: "squareMetersGarden", value: empty, text: 'מ"ר גינה', notReuired: true },
  { type: "description", value: empty, text: "תיאור" },
  { type: "assetType", value: empty, text: "סוג נכס" },
  { type: "assetState", value: empty, text: "מצב הנכס" },
  { type: "price", value: empty, text: "מחיר" , notReuired: true},
  { type: "balconies", value: 0, text: "מרפסות", notReuired: true },
  { type: "entranceDate", value: new Date().toLocaleDateString(), text: "תאריך כניסה", name: 'date' , notReuired: true},
  { type: "parking", value: empty, text: "חניה", name: "attributes" },
  { type: "exclusivity", value: empty, text: "בלעדיות", name: "attributes" },
  { type: "airConditioned", value: empty, text: "מיזוג", name: "attributes" },
  { type: "kitchen", value: empty, text: "מטבח", name: "attributes" },
  { type: "kosherKithecn", value: empty, text: "מטבח כשר", name: "attributes" },
  { type: "lift", value: empty, text: "מעלית", name: "attributes" },
  { type: "bars", value: empty, text: "סורגים", name: "attributes" },
  { type: "renovated", value: empty, text: "משופץ", name: "attributes" },
  { type: "disabledAccess", value: empty, text: "גישה לנכים", name: "attributes" },
  { type: "safeSpace", value: empty, text: 'ממ"ד', name: "attributes" },
  { type: "pandorDoor", value: empty, text: "דלתות פנדור", name: "attributes" },
  { type: "warehouse", value: empty, text: "מחסן", name: "attributes" },
  { type: "furniture", value: empty, text: "ריהוט", name: "attributes" },
  { type: "livingUnit", value: empty, text: "יחדית דיור", name: "attributes" },
  { type: "tadiranAirConditioned", value: empty, text: "מזגן תדיראן", name: "attributes" },
  { type: "furnitureDescription", value: empty, text: "תיאור ריהוט" , notReuired: true},
  { type: "images", value: empty, text: "תמונות" , notReuired: true},
  { type: "videos", value: empty, text: "סרטונים" , notReuired: true}
];
